### ISSUE TITLE
Question: The execution logic of the package

### ISSUE THREAD

**Issue by Jungle-13** [rozsasarpi/Code-calibration-Belarus#3]
Thank you ,Sir! I want to know that in what order should this whole set of codes be run, or what is the logic of this set of codes?

**Comment by rozsasarpi** [comment]
### Running the code

Running the calibration: run `main.m`. This will also save the results in a mat file and create some plots, see the bottom of `main.m`. The idea is that once you defined your problem you will need to interact (run) only this single file (`main.m`).

### Logic of the set of codes

Note that it is particular to the cases considered in the related paper but of course you can adapt it to your needs.

A brief sketch of the logic.

* `main.m`
  - main file  
  - running the calibration (`CALIBRATION` section)
  - contains some general settings, e.g. objective function to be used, target reliability, actions to be considered, etc. (see the `OPTIONS & MODEL SPECIFICATION` section)
* all the relevant inputs and settings that define a calibration problem are collected in the `Model` struct.
* all the relevant results from calibration are collected in the `Results` struct.
* the above two are passed around in most high level functions.
* `model_spec`: definition/specification of the models for the calibration, e.g. distribution function of the random variables, weights to be used for design scenarios (based on load ratios).
* `model_check`: a basic check if the inputs and settings are consistent in `Model` (should follow `model_spec`).
* `calibrate`
  - performs the optimization
  - in the objective function of the optimization (`obj_fun`) it loops over all leading actions, limit states, and load ratios: for each case 
    *  a partial factor based design (`pf_design`) is performed in a way that the utilization is 100%, i.e. the design value of the action equals the design value of the resistance
    * preparation for the reliability analysis (`prob_model`) the partial factor based design is connected to the "full" probabilistic representation of the variables, i.e. going from standardized representative values to distributions.
    * reliability analysis (`form_wrapper`) using FORM from FERUM.
* post-processing:  `plot_reli_vs_loadratio`, `plot_multisolu_gamma`, etc.


I hope that this helps. If you have further questions please let me know.

**Comment by Jungle-13** [comment]
Dear Sir. According to your prompt, I successfully ran the result. However, a new problem has appeared (haha), as follows:

```matlab
Index in position 2 is invalid. Array indices must be positive integers or logical values.

Error in select_Results (line 30)
     [~, solu_idx] = min(sum(bsxfun(@minus, PF(:,pf_idx), pf).^2,2));

Error in plot_multisolu_gamma (line 30)
Results2 = select_Results(Model, Results, pf_idx, pf);

Error in main (line 90)
plot_multisolu_gamma(Model, Results)
```

**Comment by rozsasarpi** [comment]
Please try if changing this line:

https://github.com/rozsasarpi/Code-calibration-Belarus/blob/c35fa2b7d3dd5dce987c512d97060f6b33fd4da3/Matlab/plot_multisolu_gamma.m#L11

to this

```matlab
pf_idx = 1;
```

solves it.

**Comment by Jungle-13** [comment]
Many thanks for you！

**Comment by rozsasarpi** [comment]
I fixed the index, see the above linked merge. Please let me know if you have further questions or the issue is solved.

**Comment by Jungle-13** [comment]
Yeah,Sir.
Another problem as follows when I got the result: 
partial_f =

    1.4940    0.8814    1.3046    0.9876    1.1832
****
Unrecognized function or variable 'plot_guides'.

Error in plot_multisolu_gamma (line 141)
    plot_guides(gca, Line)

Error in main (line 90)
plot_multisolu_gamma(Model, Results)
****

**Comment by rozsasarpi** [comment]
It as another custom dependency that you need to add to your path:
https://github.com/rozsasarpi/Plotting-Matlab/blob/1fc56ca127390009995924d1ac7590f415a43959/misc/plot_guides.m

I expect that a few more functions will be needed from the linked repository so it is probably the most convenient to add the entire content of the linked repo to your path.

**Comment by Jungle-13** [comment]
Sorry I was delayed by something, just saw your reply and I have added the file to my setup path. Luckily, I have run perfectly with your literature (**_Calibrating Partial Factors – Methodology, Input Data and Case Study of Steel Structure_**s), thank you very much for your short reply. My series of questions is over (haw-haw). I wish you good health and all the best. 
**### Best wishes!**

**Comment by Jungle-13** [comment]
Sorry I was delayed by something, just saw your reply .
I have added the file to my setup path. 
Luckily, I have run perfectly with your literature (**Calibrating Partial Factors – Methodology, Input Data and Case Study of Steel Structures**), thank you very much for your short reply. 
My series of questions is over (haw-haw). I wish you good health and all the best.
**Best wishes!**

**Comment by Jungle-13** [comment]
Sorry I was delayed by something, just saw your reply .
I have added the file to my setup path.
Luckily, I have run perfectly with your literature (**_Calibrating Partial Factors – Methodology, Input Data and Case Study of Steel Structures_**), thank you very much for your Patient and detailed reply.
My series of questions is over (haw-haw). I wish you good health and all the best.
**Best wishes!**

**Comment by rozsasarpi** [comment]
I'm glad to hear that it works. If you have a question related to the paper and/or the code in the future feel free to open an issue.

**Comment by Jungle-13** [comment]
Yeah,Sir. I will open an issuel on the Github if I have any question related to the paper and/or the code in the future.
Thank you from from the bottom of my heart.&nbsp;
Best wishes!
Zhangong Wang

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rozsasarpi/Code-calibration-Belarus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月15日(星期六) 晚上11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rozsasarpi/Code-calibration-Belarus] Question: The execution logic of the package (Issue #3)





 
I'm glad to hear that it works. If you have a question related to the paper and/or the code in the future feel free to open an issue.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
