### ISSUE TITLE
codes for multiple variable actions

### ISSUE THREAD

**Issue by Jungle-13** [rozsasarpi/Code-calibration-Belarus#5]
Dear Sir！I learned in the **pf_design.m** file that the object of your program is a single variable. So, I would like to ask, what should I do if I like to calibrate for the effect of multiple variable actions? Thank you, Sir.

**Comment by rozsasarpi** [comment]
The main structure (including the workflow) and most of the code remains the same when you have multiple variable actions. However, you will need to make changes to some files, e.g. in `pf_design.m` and `simple_gfun.m` you need to extend the load combination equations to the number of variable actions you need. Some other files should also be modified, e.g. the ones related to creating the design scenarios. Once you have a complete overview of the workflow(which file/function calls what) you will see where you need to make changes.

**Comment by Jungle-13** [comment]
Dear sir, in **section 5.2 ( Single or distinct partial factors for variable actions)**of the related paper, it shows the difference between (gamma_Q) and( gamma_I, gamma_S, gamma_W), so I want to know that these three partial factors are used separately or  together.

**Comment by rozsasarpi** [comment]
The three partial factors are calibrated  simultaneously (in a single optimization run) but their combination is not considered in the design equations and corresponding performance functions, i.e. for each scenario (design) there is only a single variable action without any accompanying action.

**Comment by Jungle-13** [comment]
Thank you,Sir.thank you for your reply. I have one last question, I would like to ask how do I make picture 2, picture 4, picture 7 and picture 8 (hawhaw) in the paper, other pictures can be made, but I don't know how to make these pictures . I mean, there are some function files in the code that I'm not very good at calling. thank you!

**Comment by rozsasarpi** [comment]
I could not test it but I think these are the files that produce the mentioned figures:
* Fig 8: [`compare_EC_vs_recomm.m`](https://github.com/rozsasarpi/Code-calibration-Belarus/blob/b899dfb230d9a3fc8ed4131406e4d57992ce5539/Matlab/compare_EC_vs_recomm.m),
* Fig 2 & 7: [`plot_snip_interval.m`](https://github.com/rozsasarpi/Code-calibration-Belarus/blob/b899dfb230d9a3fc8ed4131406e4d57992ce5539/Matlab/interval_analysis/plot_snip_interval.m),
* Fig 4: [`postp_distinct_gamma.m`](https://github.com/rozsasarpi/Code-calibration-Belarus/blob/b899dfb230d9a3fc8ed4131406e4d57992ce5539/Matlab/postp_distinct_gamma.m).

Most require that you have completed some analyses (calibrations) before and you saved the results in mat files.

I hope that this helps and please let me know if you have troubles reproducing the plots (At the moment I do not have the needed Matlab dependencies to check the codes locally myself).

**Comment by Jungle-13** [comment]
Thank you，dear Sir.
Best wishes！

**Comment by rozsasarpi** [comment]
@Jungle-13 please let me know if your issue is solved so I can merge the branch and close the issue.

**Comment by Jungle-13** [comment]
Yeah,Sir. I've got the answer I want. I have solved this problem.
