### ISSUE TITLE
Get the fig8 of the related paper(Nadolski, V., Rózsás, Á., Sýkora, M. "Calibrating Partial Factors – Methodology, Input Data and Case Study of Steel Structures", Periodica  Polytechnica Civil Engineering, 63(1), pp. 222–242, 2019. https://doi.org/10.3311/PPci.12822)

### ISSUE THREAD

**Issue by Jungle-13** [rozsasarpi/Code-calibration-Belarus#7]
Dear Sir, Sorry to disturb you again:

After a period of study, I have basically mastered this set of procedures. However, I don't know how to get **fig 8** of the paper(**Nadolski, V., Rózsás, Á., Sýkora, M. "Calibrating Partial Factors – Methodology, Input Data and Case Study of Steel Structures", Periodica Polytechnica Civil Engineering, 63(1), pp. 222–242, 2019. https://doi.org/10.3311/PPci.12822**).

Would it be convenient for you to tell me, Sir? Or can you send me the relevant program code?

Thank you and LOOK forward to your reply.
Best wishes!
Zhangong Wang

**Comment by rozsasarpi** [comment]
@Jungle-13 I'm glad to hear that you could make sense of the code.

Could you try running [`compare_EC_vs_recomm.m`](https://github.com/rozsasarpi/Code-calibration-Belarus/blob/72a70f8eea4d09c149a64b6096f8ba22855d0d49/Matlab/compare_EC_vs_recomm.m) and see if it produces the desired output (figure 8)?

**Comment by Jungle-13** [comment]
Dear Sir:
Thanks for your reply, I found the compare_EC_vs_recomm.m file in your latest uploaded package on GitHub, tried it and ran it successfully and my confusion was resolved.
I think this issue can also be put to an end (hawhaw).
I am very happy, thank you very much.
best wishes.
Zhangong Wang
